### ISSUE TITLE
Beacon Sensor Update Infrequent

### ISSUE THREAD

**Issue by pgavigan** [NMAI-lab/saviRoomba#28]
Beacon sensor update seems to be very infrequent. Unsure how to increase the frequency of the beacon update, but it seems to take over 10 seconds or up to a minute to get a beacon message.

This needs to be much more frequent. What options are there for increasing the beacon refresh rate?

**Comment by Simon-Yacoub** [comment]
I will look into this issue.

**Comment by Simon-Yacoub** [comment]
I believe I have found the reason for the infrequent updates. The BeaconSensor.py scripts takes 10 samples when reading beacon information. The script then removes outliers and averages the data. This greatly improved the accuracy of the readings but is now causing a jam since each sample takes 1 sec (10 seconds total). 

The obvious solution is to reduce the sample size and publish more often but, this will reduce accuracy. Perhaps we can leave it to the perception translator or agent to filter out outliers. Let me know what you think.

**Comment by Simon-Yacoub** [comment]
I am going to go ahead and start experimenting with the sampling and publishing rates and will open up a new branch. Maybe I can find a happy medium between speed and accuracy.

**Comment by pgavigan** [comment]
Thank you, please experent with it. Also, parameterize those setting so
that it can be easily timed later if needed.

**Comment by Simon-Yacoub** [comment]
So after some experimenting, I think I might have caught on to why the publishing is so infrequent. Basically, the BeaconSensor.py is taking 10 samples for each Beacon in the beacon's CSV file (50 samples total). Whenever a sample is deemed an outlier it is trashed and a new sample will be taken until one is recorded that is not an outlier. Then, once each beacon has 10 valid samples, it will average these and publish the information. I believe this is the cause of the infrequency.

**Comment by pgavigan** [comment]
Could this averaging be changed to a windowed average? Have the average be
of the previous n-1 samples and the most recent sample. That way we don't
have to wait for a it to getnn good samples, just one good sample.

**Comment by Simon-Yacoub** [comment]
Yeah, I am looking into changing the sampling method. A simpler solution I was also considering is to reduce the sample rate so it would take less time to get all valid samples.

**Comment by pgavigan** [comment]
I'd rather avoid changing the sample rate if possible.
